name: Print to PDF

on:
  push:
    branches: [ master ]

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install software
      run: sudo apt-get install -y enscript ghostscript
    - name: create pdf (each file on own page)
      run: |
        enscript -R --file-align=2 --highlight --line-numbers --color -o - `find . \\( -name '*.java' -or -name '*.gradle' \\) -and -not -path './FtcRobotController/*'` | ps2pdf - EachOnOwnPage.pdf
        enscript -R --highlight --line-numbers --color -o - `find . \\( -name '*.java' -or -name '*.gradle' \\) -and -not -path './FtcRobotController/*'` | ps2pdf - EcoFriendly.pdf
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Reports (Download)
        path: "*.pdf"
